[
  {
    _index: "luck4herhack",
    _id: "52396",
    _score: 1.0,
    _source: {
      id: "52396",
      buyer_or_seller: "Buyer",
      company_name: "GreenPlastics SA",
      email: "buyer2@example.com",
      material_cat: "PVC",
      product_cat: "Clothing",
      color: "black",
      weight: "1800",
      street: "Sustainable Street",
      zip_code: "4051",
      canton: "Basel-City",
      city: "Basel",
    },
  },
  {
    _index: "luck4herhack",
    _id: "76460",
    _score: 1.0,
    _source: {
      id: "76460",
      buyer_or_seller: "Buyer",
      company_name: "GreenWave SA",
      email: "greenwave@example.com",
      material_cat: "PVC",
      product_cat: "Clothing",
      color: "transparent",
      weight: "1800",
      street: "Eco-Fashion Avenue",
      zip_code: "9000",
      canton: "St. Gallen",
      city: "St. Gallen",
    },
  },
  {
    _index: "luck4herhack",
    _id: "11599",
    _score: 1.0,
    _source: {
      id: "11599",
      buyer_or_seller: "Buyer",
      company_name: "AV Bürge AG",
      email: "avburge@example.com",
      material_cat: "PVC",
      product_cat: "Inflatable structures",
      color: "transparent",
      weight: "1500",
      street: "Bürge Avenue",
      zip_code: "8000",
      canton: "Zurich",
      city: "Zurich",
    },
  },
  {
    _index: "luck4herhack",
    _id: "44072",
    _score: 1.0,
    _source: {
      id: "44072",
      buyer_or_seller: "Buyer",
      company_name: "GreenWave SA",
      email: "greenwave@example.com",
      material_cat: "PVC",
      product_cat: "Clothing",
      color: "red",
      weight: "1800",
      street: "Eco-Fashion Avenue",
      zip_code: "9000",
      canton: "St. Gallen",
      city: "St. Gallen",
    },
  },
  {
    _index: "luck4herhack",
    _id: "57702",
    _score: 1.0,
    _source: {
      id: "57702",
      buyer_or_seller: "Seller",
      company_name: "Oechsler AG",
      email: "oechsler@example.com",
      material_cat: "PVC",
      product_cat: "Inflatable structures",
      color: "black",
      weight: "1400",
      street: "Oechsler Lane",
      zip_code: "8004",
      canton: "Zurich",
      city: "Zurich",
    },
  },
  {
    _index: "luck4herhack",
    _id: "63711",
    _score: 1.0,
    _source: {
      id: "63711",
      buyer_or_seller: "Buyer",
      company_name: "Prodex Technologie AG",
      email: "prodextechnologie@example.com",
      material_cat: "PVC",
      product_cat: "Bags",
      color: "white",
      weight: "2300",
      street: "Prodex Technologie Street",
      zip_code: "8010",
      canton: "Zurich",
      city: "Zurich",
    },
  },
  {
    _index: "luck4herhack",
    _id: "91625",
    _score: 1.0,
    _source: {
      id: "91625",
      buyer_or_seller: "Seller",
      company_name: "Prodex Technologie AG",
      email: "prodextechnologie@example.com",
      material_cat: "PVC",
      product_cat: "Bags",
      color: "brown",
      weight: "2300",
      street: "Prodex Technologie Street",
      zip_code: "8010",
      canton: "Zurich",
      city: "Zurich",
    },
  },
  {
    _index: "luck4herhack",
    _id: "55993",
    _score: 1.0,
    _source: {
      id: "55993",
      buyer_or_seller: "Buyer",
      company_name: "GreenWave SA",
      email: "greenwave@example.com",
      material_cat: "PVC",
      product_cat: "Inflatable structures",
      color: "transparent",
      weight: "1800",
      street: "Eco-Fashion Avenue",
      zip_code: "9000",
      canton: "St. Gallen",
      city: "St. Gallen",
    },
  },
  {
    _index: "luck4herhack",
    _id: "90900",
    _score: 1.0,
    _source: {
      id: "90900",
      buyer_or_seller: "Seller",
      company_name: "Sika Schweiz AG",
      email: "sikaschweiz@example.com",
      material_cat: "PVC",
      product_cat: "Clothing",
      color: "black",
      weight: "1300",
      street: "Sika Lane",
      zip_code: "8005",
      canton: "Zurich",
      city: "Zurich",
    },
  },
  {
    _index: "luck4herhack",
    _id: "46462",
    _score: 1.0,
    _source: {
      id: "46462",
      buyer_or_seller: "Buyer",
      company_name: "Sika Schweiz AG",
      email: "sikaschweiz@example.com",
      material_cat: "PVC",
      product_cat: "Clothing",
      color: "blue",
      weight: "1300",
      street: "Sika Lane",
      zip_code: "8005",
      canton: "Zurich",
      city: "Zurich",
    },
  },
];
